//! Compile-time scan of `src/bin/ai/tool_descriptions/*.json` that generates
//! a manifest of built-in tool description files for runtime loading.
//!
//! Design: build.rs only lists the directory; it does not parse JSON. The
//! generated constant embeds each file's contents via `include_str!`; JSON
//! parsing happens lazily on first access at runtime (via `OnceLock`).

use std::fs;
use std::path::Path;

fn main() {
    let dir = Path::new("src/bin/ai/tool_descriptions");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(read_dir) = fs::read_dir(dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            let stem = match path.file_stem().and_then(|s| s.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            // Use paths relative to src/bin/ai/ (include_str! resolves relative
            // to the generated file in OUT_DIR, so we anchor back at
            // CARGO_MANIFEST_DIR).
            let rel = path.to_string_lossy().replace('\\', "/");
            entries.push((stem, rel));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("tool_description_files.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. Do not edit.\n");
    code.push_str("// Each tuple is (tool_name, file_content). JSON parsed at runtime.\n");
    code.push_str("pub(crate) const BUILTIN_TOOL_DESCRIPTION_FILES: &[(&str, &str)] = &[\n");
    for (name, rel) in &entries {
        code.push_str(&format!(
            "    ({name:?}, include_str!(\"{manifest}/{rel}\")),\n",
            manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap(),
            name = name,
            rel = rel,
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("failed to write tool_description_files.rs");
}
