//! 编译期扫描 `src/bin/ai/tool_descriptions/*.json`，
//! 生成内置工具描述文件清单，供运行时加载。
//!
//! 设计：build.rs 只列目录、不解析 JSON。生成的常量用 `include_str!`
//! 嵌入每个文件内容；JSON 解析在运行时首次访问时完成（`OnceLock`）。

use std::fs;
use std::path::Path;

fn main() {
    let dir = Path::new("src/bin/ai/tool_descriptions");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(read_dir) = fs::read_dir(dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            let stem = match path.file_stem().and_then(|s| s.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            // 使用相对于 src/bin/ai/ 的路径（include_str! 在生成文件中解析，
            // 生成文件位于 OUT_DIR，因此需要回到 CARGO_MANIFEST_DIR）。
            let rel = path.to_string_lossy().replace('\\', "/");
            entries.push((stem, rel));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("tool_description_files.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. Do not edit.\n");
    code.push_str("// Each tuple is (tool_name, file_content). JSON parsed at runtime.\n");
    code.push_str("pub(crate) const BUILTIN_TOOL_DESCRIPTION_FILES: &[(&str, &str)] = &[\n");
    for (name, rel) in &entries {
        code.push_str(&format!(
            "    ({name:?}, include_str!(\"{manifest}/{rel}\")),\n",
            manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap(),
            name = name,
            rel = rel,
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("failed to write tool_description_files.rs");
}
